apiVersion: v1
kind: Service
metadata:
  name: vpronginx
  labels:
    app: vproginx
spec:
  type: ClusterIP
  selector:
    app: vproginx
  ports:
    - port: 80
      targetPort: nginx-port
      protocol: TCP
