{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vpro-ingress
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.app.service.name | quote }}
                port:
                  number: {{ $.Values.app.port }}
  {{- end }}
{{- end }}

{{- if and .Values.ingress.enabled .Values.nginx.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vpro-nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /naveen(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $.Values.nginx.service.name | quote }}
                port:
                  number: {{ $.Values.nginx.port }}
  {{- end }}
{{- end }}