apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nginx.name }}
  labels:
    app: {{ .Values.nginx.name }}
spec:
  replicas: {{ .Values.nginx.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.nginx.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.nginx.name }}
    spec:
      containers:
      - name: nginx
        image: {{ .Values.nginx.image }}
        imagePullPolicy: {{ .Values.nginx.imagePullPolicy }}
        ports:
        - name: nginx-port
          containerPort: {{ .Values.nginx.port }}

