apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rabbitmq.service.name }}
  labels:
    app: {{ .Values.rabbitmq.name }}
spec:
  type: {{ .Values.rabbitmq.service.type }}
  selector:
    app: {{ .Values.rabbitmq.name }}
  ports:
    - port: {{ .Values.rabbitmq.port }}
      targetPort: vpromq01-port
      protocol: TCP
